version: '3.8'

services:
  portfolium:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://portfolium:portfolium2026@postgres-program-multi-byte-sensor-hqsb26:5432/portfolium
      - NEXTAUTH_SECRET=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIE5leHRBdXRo
      - NEXTAUTH_URL=https://portfolium.wolrac.com
      - NODE_ENV=production
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
